import http from 'node:http'
import { randomUUID } from 'node:crypto'
import { getMeasurementSchema, influxQuery, influxWrite, listDatabases, listMeasurements, normalizeEndpoint } from './influx-client.mjs'

const HOST='127.0.0.1',PORT=Number(process.env.GEMINIDB_BRIDGE_PORT||8790),sessions=new Map()
const MOCK_DATABASES=['monitoring','observability','maas_archive']
const MOCK_TABLES={monitoring:['t_maas_monitor_metrics_basic_m_1784563200','t_maas_monitor_metrics_basic_m_1784649600','maas_monitor_measurements_1784563200','maas_monitor_measurements_1784649600'],observability:['trace_span_metrics_1784563200','trace_span_metrics_1784649600','service_health_1784649600'],maas_archive:['archived_metrics_1784390400','archived_metrics_1784476800']}
const MOCK_ROWS=[{timestamp:'2026-07-22 11:48:03',host:'maas-node-07',metric:'cpu_usage',value:37.82,unit:'percent',status:'healthy'},{timestamp:'2026-07-22 11:47:03',host:'maas-node-03',metric:'memory_usage',value:68.41,unit:'percent',status:'healthy'},{timestamp:'2026-07-22 11:46:03',host:'maas-node-11',metric:'disk_iops',value:1248,unit:'ops/s',status:'warning'}]
const MOCK_SCHEMA={fields:[{name:'value',type:'float'},{name:'status',type:'string'},{name:'unit',type:'string'}],tags:['host','metric','region']}

function json(response,status,payload){response.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET,POST,OPTIONS'});response.end(status===204?'':JSON.stringify(payload))}
async function body(request){const chunks=[];for await(const chunk of request)chunks.push(chunk);if(!chunks.length)return{};try{return JSON.parse(Buffer.concat(chunks).toString('utf8'))}catch{throw new HttpError(400,'INVALID_JSON','请求 JSON 格式无效')}}
function delay(ms){return new Promise(resolve=>setTimeout(resolve,ms))}
class HttpError extends Error{constructor(status,code,message){super(message);this.status=status;this.code=code}}
function getSession(request){const token=(request.headers.authorization||'').replace(/^Bearer\s+/i,''),current=sessions.get(token);if(!current)throw new HttpError(401,'SESSION_REQUIRED','连接会话不存在或已失效，请重新登录');return current}
function isQuery(sql){return /^(select|show|describe|explain)\b/i.test(sql)}

async function login(data){const mode=data.mode==='influx'?'influx':'mock',config={mode,endpoint:'',username:String(data.username||''),password:String(data.password||''),insecureSkipVerify:Boolean(data.insecureSkipVerify),readOnly:Boolean(data.readOnly),timeoutMs:15000};if(mode==='influx'){if(!data.endpoint)throw new HttpError(400,'ENDPOINT_REQUIRED','请输入 GeminiDB Influx 实例地址');if(!config.username)throw new HttpError(400,'USERNAME_REQUIRED','请输入用户名');config.endpoint=normalizeEndpoint(String(data.endpoint));await listDatabases(config)}else await delay(80);const sessionId=randomUUID();sessions.set(sessionId,config);setTimeout(()=>sessions.delete(sessionId),8*60*60*1000).unref();return{sessionId,mode,endpoint:config.endpoint,readOnly:config.readOnly,expiresAt:new Date(Date.now()+8*60*60*1000).toISOString()}}
async function execute(current,database,sql){if(!sql)throw new HttpError(400,'EMPTY_SQL','命令不能为空');if(/^select\b/i.test(sql)&&!/\bwhere\b[\s\S]*\btime\b[\s\S]*(?:>=|<=|>|<)/i.test(sql))throw new HttpError(400,'TIME_RANGE_REQUIRED','SELECT 必须包含 time 范围，例如：WHERE time >= now() - 1h');if(/^write\s+/i.test(sql)&&current.readOnly)throw new HttpError(403,'READ_ONLY_CONNECTION','当前连接为只读，禁止 WRITE');if(current.mode==='mock'){const started=performance.now();await delay(120);if(/\bsyntax_error\b/i.test(sql))throw new HttpError(400,'GDB_SQL_ERROR','SQL syntax error near syntax_error');if(isQuery(sql))return{rows:MOCK_ROWS,rowCount:MOCK_ROWS.length,durationMs:Math.round(performance.now()-started),hasMore:false};return{affectedRows:1,durationMs:Math.round(performance.now()-started),message:/^write\b/i.test(sql)?'line protocol 写入成功':'命令执行成功'}}if(/^use\b/i.test(sql))return{affectedRows:0,durationMs:0,message:'database 上下文已切换'};if(/^write\s+/i.test(sql))return influxWrite(current,database,sql.replace(/^write\s+/i,''));if(/^insert\b/i.test(sql))throw new HttpError(400,'USE_LINE_PROTOCOL','GeminiDB Influx 不支持 SQL INSERT，请使用：WRITE measurement,tag=value field=1i timestamp');if(!isQuery(sql))throw new HttpError(400,'UNSUPPORTED_COMMAND','仅支持 InfluxQL 查询或 WRITE line protocol');const result=await influxQuery(current,database,sql);return{rows:result.rows,rowCount:result.rows.length,durationMs:result.durationMs,hasMore:false}}

const server=http.createServer(async(request,response)=>{const url=new URL(request.url||'/',`http://${HOST}:${PORT}`);if(request.method==='OPTIONS')return json(response,204,{});try{if(url.pathname==='/health')return json(response,200,{status:'ok',modes:['mock','influx'],version:'0.3.0'});if(url.pathname==='/login'&&request.method==='POST')return json(response,200,await login(await body(request)));const current=getSession(request);if(url.pathname==='/databases'&&request.method==='GET')return json(response,200,current.mode==='mock'?MOCK_DATABASES:await listDatabases(current));if(url.pathname==='/tables'&&request.method==='GET'){const database=url.searchParams.get('database')||'';if(!database)throw new HttpError(400,'DATABASE_REQUIRED','缺少 database');if(current.mode==='mock')return json(response,200,MOCK_TABLES[database]||[]);return json(response,200,await listMeasurements(current,database))}if(url.pathname==='/schema'&&request.method==='GET'){const database=url.searchParams.get('database')||'',measurement=url.searchParams.get('measurement')||'';if(!database||!measurement)throw new HttpError(400,'SCHEMA_CONTEXT_REQUIRED','缺少 database 或 measurement');return json(response,200,current.mode==='mock'?MOCK_SCHEMA:await getMeasurementSchema(current,database,measurement))}if(url.pathname==='/query'&&request.method==='POST'){const data=await body(request);return json(response,200,await execute(current,String(data.database||''),String(data.sql||'').trim()))}if(url.pathname==='/ask'&&request.method==='POST'){const data=await body(request),sql=String(data.sql||'');await delay(180);return json(response,200,{answer:data.error?`命令执行失败：${data.error}。请确认 database、measurement、字段和时间范围。`:'这是 GeminiDB Influx 命令。查询必须限制时间范围；写入请使用 WRITE 加 line protocol。',suggestedSql:isQuery(sql)?`EXPLAIN ${sql}`:sql})}throw new HttpError(404,'NOT_FOUND','接口不存在')}catch(error){const status=error instanceof HttpError?error.status:502,code=error instanceof HttpError?error.code:'INFLUX_UPSTREAM_ERROR';return json(response,status,{code,message:error instanceof Error?error.message:'Bridge 内部错误',requestId:randomUUID()})}})
server.listen(PORT,HOST,()=>console.log(`GeminiDB Bridge listening on http://${HOST}:${PORT} (mock + influx)`))
