export type KnowledgeCategory = '产品与模型'|'数据建模'|'写入数据'|'查询基础'|'Schema 探索'|'聚合分析'|'时间处理'|'数据管理'|'性能实践'|'排错指南'|'兼容说明'

export type KnowledgeEntry = {
  id:string
  category:KnowledgeCategory
  kind?:'concept'|'syntax'
  title:string
  content:string
  syntax:string
  example:string
  keywords:string[]
  tips?:string[]
  risk?:'write'|'danger'
}

export const KNOWLEDGE_ENTRIES:KnowledgeEntry[] = [
  {id:'geminidb-compatibility',category:'兼容说明',kind:'concept',title:'GeminiDB Influx 兼容范围',content:'GeminiDB Influx 面向 InfluxDB 1.x 生态，查询语言以 InfluxQL 1.7、1.8 为主，不支持 Flux。迁移或编写查询前，应先确认目标实例开放的函数、管理命令、账号权限与读写策略；兼容 InfluxQL 不等于所有 InfluxDB 产品能力都完全相同。',syntax:'InfluxQL 1.7 / 1.8',example:'SHOW DATABASES',keywords:['GeminiDB','InfluxDB','兼容','Flux','版本'],tips:['本知识库中的语句以 InfluxQL 1.x 为基准。','涉及创建、删除、保留策略等管理能力时，以当前实例返回结果为准。']},
  {id:'select-basic',category:'查询基础',title:'SELECT 查询数据',content:'查询指定 Measurement 的 Field 和 Tag。标识符包含特殊字符或与关键字重名时使用双引号。',syntax:'SELECT <field> FROM <measurement> [WHERE ...] [ORDER BY ...] [LIMIT n]',example:'SELECT * FROM "$measurement" ORDER BY time DESC LIMIT 100',keywords:['select','from','measurement','field','查询']},
  {id:'where-filter',category:'查询基础',title:'WHERE 条件过滤',content:'可按 Field、Tag 和 time 过滤。字符串值使用单引号，标识符使用双引号。',syntax:'WHERE <condition> [(AND|OR) <condition> ...]',example:'SELECT * FROM "$measurement" WHERE "host" = \'node-01\' AND time >= now() - 1h LIMIT 100',keywords:['where','and','or','tag','field','过滤']},
  {id:'regex-filter',category:'查询基础',title:'正则表达式过滤',content:'使用 =~ 匹配、!~ 排除。正则可用于 Measurement、Tag 值和字符串 Field；非字符串 Field 不支持正则匹配。',syntax:'"<key>" =~ /pattern/ | "<key>" !~ /pattern/',example:'SELECT * FROM "$measurement" WHERE "host" =~ /^node-/ LIMIT 100',keywords:['regex','正则','=~','!~','匹配']},
  {id:'order-limit',category:'查询基础',title:'排序与分页',content:'按时间倒序查看最新点；LIMIT/OFFSET 控制每个序列返回的数据点，SLIMIT/SOFFSET 控制序列数量。',syntax:'ORDER BY time DESC LIMIT <n> OFFSET <n> SLIMIT <n> SOFFSET <n>',example:'SELECT * FROM "$measurement" ORDER BY time DESC LIMIT 100 OFFSET 0',keywords:['order by','limit','offset','slimit','soffset','分页','排序']},
  {id:'show-measurements',category:'Schema 探索',title:'查看 Measurements',content:'列出当前 Database 中的 Measurement，可使用正则或 Tag 条件缩小范围。',syntax:'SHOW MEASUREMENTS [WITH MEASUREMENT =~ /regex/] [WHERE <tag condition>]',example:'SHOW MEASUREMENTS',keywords:['show measurements','表','measurement','schema']},
  {id:'show-field-keys',category:'Schema 探索',title:'查看 Field Keys',content:'查看 Measurement 的 Field 名称及类型。',syntax:'SHOW FIELD KEYS [FROM <measurement>]',example:'SHOW FIELD KEYS FROM "$measurement"',keywords:['show field keys','field','类型','schema']},
  {id:'show-tag-keys',category:'Schema 探索',title:'查看 Tag Keys',content:'查看 Measurement 中可用于分组和过滤的 Tag 名称。',syntax:'SHOW TAG KEYS [FROM <measurement>]',example:'SHOW TAG KEYS FROM "$measurement"',keywords:['show tag keys','tag','schema']},
  {id:'show-tag-values',category:'Schema 探索',title:'查看 Tag Values',content:'查看指定 Tag Key 的已有值，可组合 FROM、WHERE、LIMIT 和 OFFSET。',syntax:'SHOW TAG VALUES [FROM <measurement>] WITH KEY = "<tag_key>"',example:'SHOW TAG VALUES FROM "$measurement" WITH KEY = "host" LIMIT 100',keywords:['show tag values','tag value','with key','schema']},
  {id:'count-sum-mean',category:'聚合分析',title:'COUNT / SUM / MEAN 聚合',content:'COUNT 统计非空值，SUM 求和，MEAN 求平均。聚合字段必须是对应函数支持的数据类型。',syntax:'SELECT COUNT|SUM|MEAN(<field>) FROM <measurement> [WHERE ...]',example:'SELECT MEAN("value") FROM "$measurement" WHERE time >= now() - 1h',keywords:['count','sum','mean','平均','求和','计数','聚合']},
  {id:'selectors',category:'聚合分析',title:'FIRST / LAST / MIN / MAX',content:'选择时间范围内第一个、最后一个、最小或最大 Field 值。',syntax:'SELECT FIRST|LAST|MIN|MAX(<field>) FROM <measurement>',example:'SELECT LAST("value") FROM "$measurement" WHERE time >= now() - 24h',keywords:['first','last','min','max','最新','最大','最小']},
  {id:'group-by-tag',category:'聚合分析',title:'按 Tag 分组',content:'按一个或多个 Tag Key 分组聚合。高基数 Tag 可能产生大量序列，需谨慎使用。',syntax:'GROUP BY "<tag_key>"[, "<tag_key>"]',example:'SELECT MEAN("value") FROM "$measurement" WHERE time >= now() - 1h GROUP BY "host"',keywords:['group by','tag','分组','series','序列']},
  {id:'group-by-time',category:'时间处理',title:'按时间窗口聚合',content:'将数据按固定时间窗口聚合，可用 fill 控制空窗口。',syntax:'GROUP BY time(<duration>) [fill(null|none|previous|<number>|linear)]',example:'SELECT MEAN("value") FROM "$measurement" WHERE time >= now() - 24h GROUP BY time(5m) fill(null)',keywords:['group by time','fill','窗口','降采样','时间']},
  {id:'time-range',category:'时间处理',title:'时间范围查询',content:'推荐所有数据查询都限定时间范围。支持 RFC3339 时间字符串、Unix 时间戳及 now() 配合 duration。',syntax:'WHERE time >= <start> AND time < <end>',example:'SELECT * FROM "$measurement" WHERE time >= now() - 1h AND time < now() ORDER BY time DESC',keywords:['time','now','duration','时间范围','rfc3339','时间戳']},
  {id:'tz-clause',category:'时间处理',title:'TZ 时区显示',content:'TZ 子句可让返回时间按指定时区显示；过滤条件仍应明确对应的时间点。',syntax:'SELECT ... FROM ... [WHERE ...] TZ(\'<timezone>\')',example:'SELECT * FROM "$measurement" WHERE time >= now() - 1h TZ(\'Asia/Shanghai\')',keywords:['tz','timezone','时区','北京时间']},
  {id:'show-databases',category:'数据管理',title:'查看 Databases',content:'列出当前实例可见的 Database。Studio 顶部可直接切换 Database，无需执行 USE。',syntax:'SHOW DATABASES',example:'SHOW DATABASES',keywords:['show databases','database','数据库']},
  {id:'retention-policies',category:'数据管理',title:'查看保留策略',content:'查看 Database 的 Retention Policy、保留时长和副本等信息。',syntax:'SHOW RETENTION POLICIES [ON <database>]',example:'SHOW RETENTION POLICIES',keywords:['show retention policies','retention policy','rp','保留策略']},
  {id:'drop-measurement',category:'数据管理',title:'删除 Measurement',content:'永久删除整个 Measurement 的数据。生产环境应保持只读；执行前必须确认目标 Database 和名称。',syntax:'DROP MEASUREMENT "<measurement>"',example:'DROP MEASUREMENT "$measurement"',keywords:['drop measurement','删除','危险'],risk:'danger'},
  {id:'what-is-influx',category:'产品与模型',kind:'concept',title:'InfluxDB 是什么',content:'InfluxDB 是围绕时间戳组织数据的时序数据库，适合持续写入并分析指标、设备遥测、监控和事件趋势。它擅长按时间范围裁剪数据、按 Tag 维度分组、按固定窗口聚合，以及计算最新值、变化率和长期趋势；设计查询时应先确定时间范围、Measurement、维度与观测值。',syntax:'Database → Retention Policy → Measurement → Point',example:'SELECT MEAN("cpu") FROM "system" WHERE time >= now() - 1h GROUP BY time(1m),"host"',keywords:['介绍','是什么','时序数据库','timeseries','监控','iot','遥测'],tips:['它不是关系型数据库：不要期待 JOIN、外键和跨表事务模型。','查询应优先限定时间范围，避免无界扫描。','Tag 负责可索引维度，Field 保存实际观测值。']},
  {id:'geminidb-architecture',category:'产品与模型',kind:'concept',title:'GeminiDB Influx 的定位',content:'GeminiDB Influx 是兼容 InfluxQL 1.7/1.8 接口的云原生时序数据库服务，面向海量时间线写入、弹性扩展和高可用场景。应用通过实例 Endpoint 访问服务，Studio 负责连接、Schema 探索、查询与受控写入；底层部署、扩缩容和存储能力由云服务管理。',syntax:'客户端 → GeminiDB Influx Endpoint → 分布式存储',example:'SHOW DATABASES',keywords:['GeminiDB','架构','云原生','分布式','高可用','扩容','介绍'],tips:['不支持 Flux。','具体命令与函数以当前实例版本、读写模式和权限为准。','生产连接应保持只读，写入和造数优先在开发或测试环境完成。']},
  {id:'data-hierarchy',category:'产品与模型',kind:'concept',title:'核心对象层级',content:'Database 是逻辑数据空间；Retention Policy 决定数据保留时长；Measurement 是同类指标集合；Tag 描述可索引维度；Field 保存被观测值；Point 由 Measurement、Tag Set、Field Set 和 time 组成。查询时可以使用 database.retention-policy.measurement 完整限定数据来源。',syntax:'database.rp.measurement + tag set + field set + timestamp',example:'SELECT * FROM "database"."autogen"."cpu" LIMIT 10',keywords:['database','rp','retention policy','measurement','tag','field','point','层级','概念'],tips:['Series 由 Measurement 与完整 Tag Set 确定。','时间戳和 Series 一起定位一个 Point。']},
  {id:'point-identity',category:'产品与模型',kind:'concept',title:'Point、Series 与唯一性',content:'Series 由 Measurement 与完整 Tag Set 确定，代表一条独立时间线；Point 则由 Series 加 timestamp 定位。同一 Measurement、相同完整 Tag Set、相同 timestamp 再次写入时，Field Set 会合并，其中重名 Field 由新值覆盖，因此重复写入既可用于更新，也可能造成意外覆盖。',syntax:'series = measurement + tag set; point = series + timestamp',example:'cpu,host=node-01 usage=60i 1785398400000000000',keywords:['point','series','唯一','重复点','覆盖','合并','time series'],tips:['Field Set 不参与 Series 身份。','误用随机值做 Tag 会制造大量 Series。','更新前必须保留原 Point 的完整 Tag Set 和精确时间戳。']},
  {id:'measurement-concept',category:'数据建模',kind:'concept',title:'Measurement 完整理解',content:'Measurement 是同类时序数据的逻辑集合，作用近似关系库中的表名，但没有固定行结构。一个 Measurement 内的不同 Point 可以拥有不同 Field；查询、保留策略、Series 基数和数据生命周期分析通常都围绕 Measurement 展开。设计时应让名称代表稳定的业务指标，而把设备、区域等变化维度放进 Tag。',syntax:'<measurement>[,<tags>] <fields> <timestamp>',example:'temperature,site=shanghai value=26.3,humidity=71i 1785398400000000000',keywords:['measurement','表','指标','模型','定义','知识'],tips:['名称区分大小写。','不要把设备 ID 拼进 Measurement；通常应建成 Tag。','按业务指标稳定命名，避免无界创建新名称，除非系统明确采用天表设计。']},
  {id:'measurement-naming',category:'数据建模',title:'Measurement 命名与引用',content:'建议使用稳定、可读、低变化的名称。查询时用双引号包围名称，尤其是包含空格、特殊字符或 InfluxQL 关键字时。Line Protocol 写入端不是靠引号转义，而是反斜杠。',syntax:'查询: FROM "<measurement>"；写入: measurement\\ name',example:'SELECT * FROM "cpu load" LIMIT 10',keywords:['measurement','命名','双引号','转义','关键字','大小写']},
  {id:'tag-vs-field',category:'数据建模',kind:'concept',title:'Tag 还是 Field',content:'Tag 值始终是字符串并建立索引，适合经常用于过滤或 GROUP BY 的有限枚举维度；Field 保存实际观测值，支持数值、字符串和布尔类型，可参与聚合，但不建立与 Tag 相同的索引。判断原则不是“是否重要”，而是它是否属于有界维度、是否经常用于定位 Series。',syntax:'tag: host=node-01；field: usage=72.5',example:'cpu,host=node-01,region=cn-east usage=72.5,cores=8i',keywords:['tag','field','区别','索引','维度','数值','建模'],tips:['设备、区域、状态类别通常做 Tag。','温度、利用率、计数器通常做 Field。','用户 ID、请求 ID 等高基数字段慎做 Tag。']},
  {id:'schema-cardinality',category:'数据建模',kind:'concept',title:'Series 基数为何重要',content:'Series 基数近似为 Measurement 与所有 Tag Key/Value 组合的唯一数量。每增加一个高变化 Tag，组合数都可能成倍增长，从而提高索引、内存与查询扫描成本；高基数是时序数据库最常见、也最隐蔽的建模风险之一。',syntax:'series cardinality ≈ unique(measurement + complete tag set)',example:'SHOW SERIES CARDINALITY',keywords:['cardinality','基数','series','高基数','内存','索引'],tips:['不要把时间戳、UUID、日志正文放进 Tag。','先估算各 Tag 组合的笛卡尔积。','定期用 Series Cardinality 观察增长趋势。']},
  {id:'field-types',category:'数据建模',kind:'concept',title:'Field 数据类型',content:'Field Value 支持 float、integer、string 和 boolean。Line Protocol 中普通数字默认是 float，整数必须添加 i 后缀，字符串必须使用双引号，布尔值不加引号。同一 Measurement 下同名 Field Key 应始终保持同一种类型，否则写入可能发生类型冲突。',syntax:'float=1.5, integer=1i, string="ok", boolean=true',example:'sensor value=12.5,count=12i,status="ok",enabled=true',keywords:['field type','float','integer','string','boolean','类型冲突'],tips:['同一 Measurement 同一 Field Key 的类型应保持一致。','12 与 12i 是不同类型。','类型选错后通常需要新 Field Key 或迁移数据，不能靠下一次写入自动修正。']},
  {id:'reserved-identifiers',category:'数据建模',kind:'concept',title:'保留字与特殊 Key',content:'建模时应避开 InfluxQL 关键字与系统保留名称。time 不能作为 Tag Key 或 Field Key；_field、_measurement 等名称也不应作为业务 Key。已有名称与关键字冲突时，查询中需要使用双引号明确它是标识符。',syntax:'避免: time, _field, _measurement, SELECT, GROUP ...',example:'SELECT "value" FROM "$measurement" LIMIT 10',keywords:['保留字','reserved','time','_field','_measurement','关键字'],tips:['新建 Schema 时优先使用稳定、含义明确的英文小写名称。']},
  {id:'insert-cli',category:'写入数据',title:'INSERT 插入一条数据',content:'Studio 中使用 INSERT 加一行 Line Protocol。第一个空格前是 Measurement 和 Tag Set，第二部分是 Field Set，最后可选时间戳。',syntax:'INSERT <measurement>[,<tag>=<value>] <field>=<value>[,<field>=<value>] [<timestamp>]',example:'INSERT temperature,site=shanghai,device=sensor-01 value=26.3,humidity=71i,status="ok",online=true 1785398400000000000',keywords:['insert','插入','新增','写数据','line protocol','一条'],tips:['Measurement 必填、Field Set 至少一个，Tag 可选。','未给时间戳时使用服务端当前时间。','生产连接在 Studio 中只读，无法执行。']},
  {id:'insert-no-tags',category:'写入数据',title:'无 Tag 的 INSERT',content:'没有维度时可省略 Tag Set；Measurement 后直接以空格分隔 Field Set。',syntax:'INSERT <measurement> <field_set> [timestamp]',example:'INSERT heartbeat alive=true,message="ok" 1785398400000000000',keywords:['insert','无tag','field','心跳','插入']},
  {id:'insert-multiple-fields',category:'写入数据',title:'一次写入多个 Field',content:'同一个 Point 的多个 Field 用逗号连接且中间不能有空格。不同 Field 可使用不同数据类型。',syntax:'field1=<value>,field2=<value>,field3=<value>',example:'INSERT device,host=node-01 cpu=62.5,memory=71.2,count=9i,healthy=true,note="normal"',keywords:['insert','多个field','批量字段','写入','逗号']},
  {id:'insert-multiple-points',category:'写入数据',title:'批量插入多条数据',content:'每行是一条完整 Line Protocol。Studio 支持多条 INSERT/WRITE 命令时应逐条验证并确认；大量造数应使用“批量造数”功能。',syntax:'INSERT <line1>;\nINSERT <line2>;',example:'INSERT temperature,device=sensor-01 value=26.3 1785398400000000000;\nINSERT temperature,device=sensor-02 value=25.8 1785398400000000000;',keywords:['insert','批量插入','多条','batch','造数']},
  {id:'line-protocol-spacing',category:'写入数据',title:'Line Protocol 空格规则',content:'Line Protocol 对空格敏感：Measurement+Tag Set 与 Field Set 之间恰好用未转义空格分隔；Field Set 与 timestamp 再用空格分隔。Tag、Field 内部使用逗号，不加空格。',syntax:'measurement,tags<SPACE>fields<SPACE>timestamp',example:'INSERT cpu,host=node-01 usage=72.5,count=3i 1785398400000000000',keywords:['空格','line protocol','bad timestamp','parse','格式']},
  {id:'line-protocol-escaping',category:'写入数据',title:'写入特殊字符转义',content:'Measurement 中的逗号和空格需反斜杠转义；Tag Key、Tag Value、Field Key 中的逗号、等号、空格需转义；字符串 Field 内的双引号和反斜杠需转义。',syntax:'\\,  \\=  \\ ；字符串内 \\" 与 \\\\',example:'INSERT weather\\ station,site=shanghai\\ pudong note="wind \\"strong\\"",value=3.2',keywords:['转义','escape','空格','逗号','等号','双引号','反斜杠']},
  {id:'timestamp-precision-write',category:'写入数据',title:'写入时间戳精度',content:'INSERT 示例默认使用 Unix 纳秒时间戳；经 HTTP /write 写入时可通过 precision 指定 n、u、ms、s、m、h。精度声明必须与数值一致。',syntax:'POST /write?db=<db>&precision=ms',example:'INSERT temperature,site=shanghai value=26.3 1785398400000000000',keywords:['timestamp','precision','ns','ms','s','纳秒','毫秒','时间戳'],tips:['精度不匹配会把数据写到错误时间。','尽量使用满足业务需要的最低精度以改善压缩。']},
  {id:'http-write',category:'写入数据',title:'HTTP API 写入',content:'应用程序通常 POST 到 /write，Database 用 db 参数，Line Protocol 放在原始请求体。多点使用换行分隔，并使用 --data-binary 保留换行。',syntax:'POST /write?db=<database>&rp=<rp>&precision=<precision>',example:'curl -i -XPOST "http://host:8086/write?db=mydb&precision=ms" --data-binary \'cpu,host=node-01 usage=72.5 1785398400000\'',keywords:['http','api','write','curl','/write','db','rp','precision']},
  {id:'duplicate-points',category:'写入数据',title:'重复 Point 的合并规则',content:'再次写入相同 Measurement、完整 Tag Set 和 timestamp 时，已有与新 Field Set 合并；同名 Field 使用新值。这是更新单个 Field 的基础，也可能造成意外覆盖。',syntax:'same measurement + same tags + same timestamp',example:'INSERT cpu,host=node-01 usage=80.0 1785398400000000000',keywords:['重复点','duplicate','覆盖','更新','合并','point']},
  {id:'field-type-conflict',category:'写入数据',title:'Field 类型冲突',content:'同一 Measurement 的同名 Field 若先写 float 后写 string/integer，通常会出现 field type conflict。修复方式是保持类型一致或使用新 Field Key。',syntax:'错误示例: value=1.0 后又写 value="1"',example:'INSERT sensor value=1.0',keywords:['field type conflict','类型冲突','写入失败','partial write'],tips:['整数务必带 i。','历史错误类型不会因后续正确写入自动转换。']},
  {id:'select-qualified',category:'查询基础',title:'完整限定 Measurement',content:'可用 Database、Retention Policy、Measurement 完整限定数据源，跨 RP 或上下文不明确时很有用。',syntax:'FROM "<database>"."<retention_policy>"."<measurement>"',example:'SELECT * FROM "mydb"."autogen"."cpu" WHERE time >= now() - 1h LIMIT 100',keywords:['fully qualified','database','retention policy','measurement','完整限定','from']},
  {id:'identifier-disambiguation',category:'查询基础',title:'Tag 与 Field 同名时消歧',content:'当 Tag Key 与 Field Key 同名，用 ::tag 或 ::field 明确类型，避免返回列后缀或条件解释错误。',syntax:'"<key>"::tag | "<key>"::field',example:'SELECT "location"::tag,"location"::field FROM "$measurement" LIMIT 10',keywords:['::tag','::field','同名','消歧','duplicate key']},
  {id:'distinct',category:'聚合分析',title:'DISTINCT 去重值',content:'返回 Field 的唯一值；若只想看 Tag 的已有值，应优先使用 SHOW TAG VALUES。',syntax:'SELECT DISTINCT("<field>") FROM <measurement> [WHERE ...]',example:'SELECT DISTINCT("status") FROM "$measurement" WHERE time >= now() - 24h',keywords:['distinct','去重','唯一值','field']},
  {id:'median-mode-spread',category:'聚合分析',title:'MEDIAN / MODE / SPREAD',content:'MEDIAN 求中位数，MODE 求众数，SPREAD 返回最大值减最小值，适合分布与波动分析。',syntax:'SELECT MEDIAN|MODE|SPREAD("<field>") FROM <measurement>',example:'SELECT MEDIAN("value"),SPREAD("value") FROM "$measurement" WHERE time >= now() - 1h',keywords:['median','mode','spread','中位数','众数','极差']},
  {id:'percentile',category:'聚合分析',title:'PERCENTILE 分位数',content:'计算数值 Field 的指定百分位，用于延迟 P95/P99 等指标。',syntax:'PERCENTILE("<field>", <N>)',example:'SELECT PERCENTILE("latency_ms",95) FROM "$measurement" WHERE time >= now() - 1h GROUP BY time(5m)',keywords:['percentile','p95','p99','分位数','延迟']},
  {id:'top-bottom',category:'聚合分析',title:'TOP / BOTTOM',content:'返回最大或最小的 N 个 Field 值，可附带 Tag/Field 作为辅助列。',syntax:'TOP|BOTTOM("<field>", [<tag_or_field>,] <N>)',example:'SELECT TOP("value",5) FROM "$measurement" WHERE time >= now() - 1h',keywords:['top','bottom','最高','最低','排名']},
  {id:'derivative-difference',category:'聚合分析',title:'DERIVATIVE / DIFFERENCE',content:'DIFFERENCE 计算相邻值之差；DERIVATIVE 按时间单位计算变化率，常用于计数器速率。',syntax:'DERIVATIVE(<function>("<field>"), <unit>) | DIFFERENCE("<field>")',example:'SELECT NON_NEGATIVE_DERIVATIVE(MEAN("bytes"),1s) FROM "$measurement" WHERE time >= now() - 1h GROUP BY time(1m)',keywords:['derivative','difference','rate','变化率','差值','counter']},
  {id:'elapsed',category:'聚合分析',title:'ELAPSED 时间间隔',content:'计算连续 Point 时间戳之间的差，并按指定单位返回，适合检查采样间隔和断点。',syntax:'ELAPSED("<field>", <unit>)',example:'SELECT ELAPSED("value",1s) FROM "$measurement" WHERE time >= now() - 1h',keywords:['elapsed','间隔','采样','断点','时间差']},
  {id:'cumulative-sum',category:'聚合分析',title:'CUMULATIVE_SUM 累计值',content:'对数值 Field 或聚合结果计算运行累计和。数据量大时先按时间窗口聚合再累计。',syntax:'CUMULATIVE_SUM("<field>")',example:'SELECT CUMULATIVE_SUM(SUM("count")) FROM "$measurement" WHERE time >= now() - 24h GROUP BY time(1h)',keywords:['cumulative_sum','累计','累加']},
  {id:'subquery',category:'查询基础',title:'子查询',content:'子查询位于 FROM 中，先生成中间结果再由外层过滤或聚合，可替代部分 HAVING 和复杂嵌套需求。',syntax:'SELECT ... FROM (SELECT ... FROM ...) WHERE ...',example:'SELECT * FROM (SELECT MEAN("value") AS avg_value FROM "$measurement" WHERE time >= now() - 24h GROUP BY time(5m)) WHERE avg_value > 80',keywords:['subquery','子查询','having','嵌套']},
  {id:'into-query',category:'数据管理',title:'SELECT INTO 写入查询结果',content:'把查询或聚合结果写入目标 Measurement，常用于手工降采样或迁移。它是写操作，必须先限定时间范围并确认目标。',syntax:'SELECT <fields> INTO <target> FROM <source> WHERE ... [GROUP BY ...]',example:'SELECT MEAN("value") AS "value" INTO "downsampled" FROM "$measurement" WHERE time >= now() - 24h GROUP BY time(5m),"host"',keywords:['select into','into','降采样','迁移','写入结果'],risk:'write',tips:['未限定时间可能扫描并写入大量历史数据。','生产环境保持只读。']},
  {id:'fill-options',category:'时间处理',title:'fill 空窗口策略',content:'GROUP BY time 后，fill(null) 返回空值、fill(none) 不返回空窗口、fill(previous) 使用前值，也可填固定数值；linear 是否可用需以实例为准。',syntax:'fill(null|none|previous|<number>|linear)',example:'SELECT MEAN("value") FROM "$measurement" WHERE time >= now() - 1h GROUP BY time(5m) fill(previous)',keywords:['fill','null','none','previous','linear','补点','空窗口']},
  {id:'group-offset',category:'时间处理',title:'时间窗口偏移',content:'GROUP BY time 支持 offset_duration 调整自然窗口边界，适合业务日或非整点周期。',syntax:'GROUP BY time(<interval>, <offset>)',example:'SELECT SUM("value") FROM "$measurement" WHERE time >= now() - 24h GROUP BY time(1h,30m)',keywords:['group by time','offset','窗口偏移','自然边界']},
  {id:'relative-time',category:'时间处理',title:'相对时间与 Duration',content:'now() 返回当前服务端时间，可与 ns、u、ms、s、m、h、d、w 等 Duration 运算。',syntax:'time >= now() - 15m',example:'SELECT * FROM "$measurement" WHERE time >= now() - 15m ORDER BY time DESC LIMIT 100',keywords:['now','duration','相对时间','15m','1h','7d']},
  {id:'absolute-time',category:'时间处理',title:'RFC3339 绝对时间',content:'绝对时间字符串使用单引号并带明确时区。推荐使用 Z 或 +08:00，避免把本地时间误当 UTC。',syntax:'time >= \'YYYY-MM-DDTHH:mm:ssZ\' AND time < \'...\'',example:'SELECT * FROM "$measurement" WHERE time >= \'2026-07-30T00:00:00+08:00\' AND time < \'2026-07-31T00:00:00+08:00\'',keywords:['rfc3339','绝对时间','utc','+08:00','时间范围']},
  {id:'show-series',category:'Schema 探索',title:'查看 Series',content:'SHOW SERIES 返回 Series Key，可按 Measurement 或 Tag 条件过滤。结果可能很大，应使用 FROM、WHERE 和 LIMIT。',syntax:'SHOW SERIES [FROM <measurement>] [WHERE <tag condition>] [LIMIT n]',example:'SHOW SERIES FROM "$measurement" LIMIT 100',keywords:['show series','series key','时间线','schema']},
  {id:'show-series-cardinality',category:'Schema 探索',title:'查看 Series 基数',content:'统计时间线数量，用于评估高基数风险。EXACT 变体通常更精确但成本更高，支持情况以 GeminiDB 实例为准。',syntax:'SHOW SERIES CARDINALITY [FROM <measurement>]',example:'SHOW SERIES CARDINALITY FROM "$measurement"',keywords:['show series cardinality','exact cardinality','基数','时间线数量']},
  {id:'show-measurement-cardinality',category:'Schema 探索',title:'查看 Measurement 数量',content:'统计可见 Measurement 数量；当业务动态创建表名时用于发现名称膨胀。',syntax:'SHOW MEASUREMENT CARDINALITY',example:'SHOW MEASUREMENT CARDINALITY',keywords:['show measurement cardinality','measurement数量','基数']},
  {id:'show-retention',category:'Schema 探索',title:'查看 RP 详情',content:'返回 RP 名称、保留时长、副本、Shard Group Duration 及是否默认等信息，是排查历史数据消失的第一步。',syntax:'SHOW RETENTION POLICIES [ON "<database>"]',example:'SHOW RETENTION POLICIES',keywords:['show retention policies','rp','duration','shard','历史数据','过期']},
  {id:'create-database',category:'数据管理',title:'创建 Database',content:'创建逻辑 Database。是否允许由实例模式、账号权限和 Studio 环境策略共同决定。',syntax:'CREATE DATABASE "<database>"',example:'CREATE DATABASE "metrics_dev"',keywords:['create database','创建数据库'],risk:'write'},
  {id:'drop-database',category:'数据管理',title:'删除 Database',content:'永久删除 Database 及其数据，是最高风险操作。执行前确认环境、连接和备份。',syntax:'DROP DATABASE "<database>"',example:'DROP DATABASE "metrics_dev"',keywords:['drop database','删除数据库','危险'],risk:'danger'},
  {id:'create-rp',category:'数据管理',title:'创建 Retention Policy',content:'设置数据保留时长、Replication 和可选 DEFAULT。GeminiDB 的复制配置约束以实例文档为准。',syntax:'CREATE RETENTION POLICY "<rp>" ON "<db>" DURATION <duration> REPLICATION <n> [DEFAULT]',example:'CREATE RETENTION POLICY "seven_days" ON "metrics_dev" DURATION 7d REPLICATION 1',keywords:['create retention policy','rp','duration','replication','default','保留策略'],risk:'write'},
  {id:'alter-rp',category:'数据管理',title:'修改 Retention Policy',content:'修改 RP 的保留时长或默认状态。缩短 Duration 可能导致旧数据被清理。',syntax:'ALTER RETENTION POLICY "<rp>" ON "<db>" DURATION <duration> [DEFAULT]',example:'ALTER RETENTION POLICY "seven_days" ON "metrics_dev" DURATION 14d DEFAULT',keywords:['alter retention policy','修改rp','duration'],risk:'danger'},
  {id:'delete-points',category:'数据管理',title:'按条件删除数据',content:'DELETE 按 Measurement、Tag 条件和时间范围删除 Point。不要对 Field 条件的支持做假设；先用同条件 SELECT 验证范围。',syntax:'DELETE FROM "<measurement>" WHERE <tag/time condition>',example:'DELETE FROM "$measurement" WHERE "host" = \'node-test\' AND time >= now() - 1h',keywords:['delete from','删除数据','按时间删除'],risk:'danger',tips:['先把 DELETE 改成 SELECT * 并核对结果。','删除不可撤销。']},
  {id:'continuous-query',category:'数据管理',title:'Continuous Query 持续降采样',content:'CQ 周期性执行 SELECT INTO，把高频原始数据聚合到低频 Measurement。创建前先用普通 SELECT 验证输出。',syntax:'CREATE CONTINUOUS QUERY "<name>" ON "<db>" BEGIN SELECT ... INTO ... FROM ... GROUP BY time(...) END',example:'CREATE CONTINUOUS QUERY "cq_5m" ON "metrics_dev" BEGIN SELECT MEAN("value") AS "value" INTO "metrics_dev"."autogen"."cpu_5m" FROM "cpu" GROUP BY time(5m),"host" END',keywords:['continuous query','cq','持续查询','降采样'],risk:'write'},
  {id:'time-bound-performance',category:'性能实践',title:'查询必须限定时间',content:'时间范围是最有效的扫描裁剪条件。线上查询避免无界 SELECT *，先用较短窗口和 LIMIT 验证。',syntax:'WHERE time >= now() - <duration>',example:'SELECT * FROM "$measurement" WHERE time >= now() - 15m ORDER BY time DESC LIMIT 100',keywords:['性能','时间范围','慢查询','扫描','limit'],tips:['LIMIT 只限制返回量，不一定替代时间裁剪。']},
  {id:'tag-filter-performance',category:'性能实践',title:'优先用 Tag 缩小 Series',content:'高选择性的 Tag 条件可减少访问的 Series；Field 条件通常发生在数据扫描阶段。建模时把常用有限维度放在 Tag。',syntax:'WHERE "host" = \'node-01\' AND time >= now() - 1h',example:'SELECT MEAN("usage") FROM "$measurement" WHERE "region" = \'cn-east\' AND time >= now() - 1h GROUP BY "host"',keywords:['性能','tag filter','索引','series','field filter']},
  {id:'avoid-select-star',category:'性能实践',title:'避免大范围 SELECT *',content:'只选择需要的 Field，限制时间和行数。SELECT * 会返回全部 Field/Tag，宽 Schema 下网络和反序列化成本明显。',syntax:'SELECT "<field1>","<field2>" FROM ... WHERE time ... LIMIT ...',example:'SELECT "usage","load" FROM "$measurement" WHERE time >= now() - 1h LIMIT 100',keywords:['select *','性能','字段裁剪','网络']},
  {id:'downsampling',category:'性能实践',title:'降采样与分层保留',content:'原始高频数据保留较短时间，按分钟/小时聚合的数据保留更久。使用 CQ 或受控 SELECT INTO 构建分层 Measurement/RP。',syntax:'raw RP → GROUP BY time → downsampled RP',example:'SELECT MEAN("value") INTO "metrics_dev"."long_term"."sensor_1h" FROM "$measurement" WHERE time >= now() - 24h GROUP BY time(1h),"device"',keywords:['降采样','downsampling','rp','cq','长期存储','成本']},
  {id:'batch-write-performance',category:'性能实践',title:'批量写入与时间精度',content:'HTTP 写入应合并为适量批次，并使用满足业务需要的最低时间精度。官方 InfluxDB v1 建议常见批次为 5,000–10,000 点，但 GeminiDB 实际上限需按实例压测。',syntax:'POST /write + newline-delimited points',example:'cpu,host=node-01 usage=71.0 1785398400000\ncpu,host=node-02 usage=63.5 1785398400000',keywords:['批量写入','batch','5000','10000','precision','压缩','性能']},
  {id:'bad-timestamp',category:'排错指南',title:'bad timestamp',content:'通常由时间戳带引号、精度与数值不一致，或 Line Protocol 空格错位导致。时间戳必须是无引号整数。',syntax:'... <field_set> <integer_timestamp>',example:'INSERT cpu,host=node-01 usage=72.5 1785398400000000000',keywords:['bad timestamp','时间戳错误','写入报错','parse'],tips:['先检查两个分隔空格的位置。','确认请求 precision 与时间戳位数。']},
  {id:'no-results',category:'排错指南',title:'查询无结果',content:'依次检查当前 Database/RP、Measurement 大小写、时间范围与时区、Tag 值引号、Field 类型和数据是否已过 RP。',syntax:'SHOW MEASUREMENTS → SHOW FIELD KEYS → SELECT ... WHERE time ...',example:'SELECT * FROM "$measurement" ORDER BY time DESC LIMIT 10',keywords:['无数据','no results','空结果','查不到','时区','rp'],tips:['字符串值使用单引号，标识符使用双引号。','先去掉非时间条件逐步缩小问题。']},
  {id:'mix-aggregate',category:'排错指南',title:'聚合与非聚合列混用',content:'同一 SELECT 中通常不能无分组地混用聚合函数与普通 Field/Tag。需要维度时用 GROUP BY Tag，需要中间结果时使用子查询。',syntax:'错误: SELECT MEAN("value"),"host" ...；正确: ... GROUP BY "host"',example:'SELECT MEAN("value") FROM "$measurement" WHERE time >= now() - 1h GROUP BY "host"',keywords:['mixing aggregate','aggregate','non-aggregate','聚合报错','group by']},
  {id:'partial-write',category:'排错指南',title:'partial write / 类型冲突',content:'部分写入常见原因包括 Field 类型冲突、超出保留策略时间、格式错误或批次中个别 Point 非法。按错误中行号/内容拆小批次定位。',syntax:'field type conflict | points beyond retention policy | parse error',example:'SHOW FIELD KEYS FROM "$measurement"',keywords:['partial write','field type conflict','写入部分失败','retention policy']},
  {id:'too-many-series',category:'排错指南',title:'Series 过多与查询变慢',content:'检查是否把 UUID、请求 ID、时间戳等无界值做成 Tag，并查看 Series 基数。短期先加 Tag/时间条件，长期需要调整 Schema。',syntax:'SHOW SERIES CARDINALITY FROM <measurement>',example:'SHOW SERIES CARDINALITY FROM "$measurement"',keywords:['too many series','高基数','慢查询','内存','cardinality']},
]

export function searchKnowledge(entries:KnowledgeEntry[], query:string, category?:KnowledgeCategory|'全部'):KnowledgeEntry[] {
  const needle=query.trim().toLocaleLowerCase()
  const tokens=needle.split(/\s+/).filter(Boolean)
  return entries.filter(item => {
    if(category&&category!=='全部'&&item.category!==category)return false
    if(!needle)return true
    const haystack=[item.title,item.category,item.content,item.syntax,item.example,...item.keywords,...(item.tips||[])].join('\n').toLocaleLowerCase()
    return haystack.includes(needle)||tokens.every(token=>haystack.includes(token))
  })
}

export function knowledgeExample(entry:KnowledgeEntry, measurement:string):string {
  const safe=(measurement||'measurement').replaceAll('"','\\"')
  return entry.example.replaceAll('$measurement',safe)
}
