import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './styles.css'
import './sidebar-polish.css'
import './data-grid.css'
import './results-scroll.css'
import './query-editor.css'
import './editor-loading.css'
import './bridge-status.css'
import './sidebar-resize.css'
import './time-dialog.css'
import './connection-dialog.css'
import './favorite-dialog.css'
import './knowledge-base.css'
import './history-table.css'
import './database-switcher.css'
import './feature-tour.css'
import './learning-center.css'
import './schema-dialog.css'
import './responsive-layout.css'
import './theme.css'
import './bulk-data.css'
import './claude-assistant.css'
import './measurement-data-view.css'
import './result-polish.css'
import './notes-workspace.css'

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode><App /></React.StrictMode>
)
