export type NoteDocument={path:string;content:string;modifiedMs:number}
export type MarkdownBlock={type:'heading';level:number;text:string}|{type:'paragraph';text:string}|{type:'list';ordered:boolean;items:string[]}|{type:'code';language:string;text:string}|{type:'table';headers:string[];rows:string[][]}

export function noteTitle(content:string,path:string){return content.match(/^#\s+(.+)$/m)?.[1].trim()||path.split('/').at(-1)?.replace(/\.md$/i,'')||'未命名'}
export function noteTags(content:string){return [...new Set([...content.matchAll(/(?:^|\s)#([\p{L}\p{N}_-]+)/gu)].map(match=>match[1]))]}
export function searchNotes(notes:NoteDocument[],query:string){const term=query.trim().toLocaleLowerCase();return !term?notes:notes.filter(note=>`${noteTitle(note.content,note.path)}\n${note.content}`.toLocaleLowerCase().includes(term))}
export function safeNoteFilename(title:string,existing:string[]){let base=title.replace(/[\\/:*?"<>|\u0000-\u001f]/g,'').trim().replace(/\.+$/,'')||'未命名';if(/^(con|prn|aux|nul|com[1-9]|lpt[1-9])$/i.test(base))base=`${base}-笔记`;const names=new Set(existing.map(path=>path.split('/').at(-1)?.toLocaleLowerCase()));let name=`${base}.md`,index=2;while(names.has(name.toLocaleLowerCase()))name=`${base} (${index++}).md`;return name}
export function appendSqlToNote(content:string,sql:string){return `${content.trimEnd()}\n\n\`\`\`influxql\n${sql.trim()}\n\`\`\`\n`}
const cells=(line:string)=>line.trim().replace(/^\||\|$/g,'').split('|').map(value=>value.trim())
export function parseMarkdown(source:string):MarkdownBlock[]{const lines=source.replace(/\r/g,'').split('\n'),blocks:MarkdownBlock[]=[];for(let i=0;i<lines.length;){const line=lines[i];if(!line.trim()){i++;continue}const fence=line.match(/^```([\w-]*)\s*$/);if(fence){const body:string[]=[];i++;while(i<lines.length&&!/^```\s*$/.test(lines[i]))body.push(lines[i++]);i++;blocks.push({type:'code',language:fence[1].toLowerCase(),text:body.join('\n')});continue}const heading=line.match(/^(#{1,6})\s+(.+)$/);if(heading){blocks.push({type:'heading',level:heading[1].length,text:heading[2]});i++;continue}if(line.includes('|')&&i+1<lines.length&&/^\s*\|?\s*:?-+/.test(lines[i+1])){const headers=cells(line),rows:string[][]=[];i+=2;while(i<lines.length&&lines[i].includes('|')&&lines[i].trim())rows.push(cells(lines[i++]));blocks.push({type:'table',headers,rows});continue}const list=line.match(/^\s*(?:([-*+])|(\d+)\.)\s+(.+)$/);if(list){const ordered=Boolean(list[2]),items:string[]=[];while(i<lines.length){const item=lines[i].match(/^\s*(?:([-*+])|(\d+)\.)\s+(.+)$/);if(!item||Boolean(item[2])!==ordered)break;items.push(item[3]);i++}blocks.push({type:'list',ordered,items});continue}const text=[line];i++;while(i<lines.length&&lines[i].trim()&&!/^(#{1,6})\s|^```|^\s*(?:[-*+]|\d+\.)\s+/.test(lines[i]))text.push(lines[i++]);blocks.push({type:'paragraph',text:text.join('\n')})}return blocks}
