import {createElement,useEffect,useMemo,useRef,useState} from 'react'
import {isTauri} from '@tauri-apps/api/core'
import {authorizeNotesDirectory,chooseNotesDirectory,deleteNote,listNotes,renameNote,writeNote,type DesktopNote} from './desktop'
import {appendSqlToNote,noteTags,noteTitle,parseMarkdown,safeNoteFilename,searchNotes} from './notes'

const DIRECTORY_KEY='gdb.notes.directory'
type Props={currentSql:string;onOpenSql:(sql:string)=>void;onNotify:(message:string)=>void}
export default function NotesWorkspace({currentSql,onOpenSql,onNotify}:Props){
 const [directory,setDirectory]=useState(()=>localStorage.getItem(DIRECTORY_KEY)||''),[notes,setNotes]=useState<DesktopNote[]>([]),[active,setActive]=useState(''),[query,setQuery]=useState(''),[preview,setPreview]=useState(false),[status,setStatus]=useState(''),saveTimer=useRef<number|undefined>(undefined)
 const current=notes.find(note=>note.path===active),filtered=useMemo(()=>searchNotes(notes,query),[notes,query])
 async function load(root=directory){if(!root)return;try{await authorizeNotesDirectory(root);const next=await listNotes();setNotes(next);setActive(value=>next.some(note=>note.path===value)?value:(next[0]?.path||''));setStatus('')}catch(error){setStatus(error instanceof Error?error.message:'无法读取笔记目录')}}
 useEffect(()=>{void load()},[])
 useEffect(()=>()=>window.clearTimeout(saveTimer.current),[])
 async function choose(){const selected=await chooseNotesDirectory();if(!selected)return;localStorage.setItem(DIRECTORY_KEY,selected);setDirectory(selected);await load(selected)}
 function update(content:string){if(!current)return;setNotes(items=>items.map(note=>note.path===active?{...note,content}:note));setStatus('保存中…');window.clearTimeout(saveTimer.current);saveTimer.current=window.setTimeout(()=>void writeNote(active,content).then(()=>setStatus('已保存')).catch(error=>setStatus(error instanceof Error?error.message:'保存失败')),700)}
 async function create(){const path=safeNoteFilename('未命名',notes.map(note=>note.path)),content='# 未命名\n';await writeNote(path,content);setNotes(items=>[{path,content,modifiedMs:Date.now()},...items]);setActive(path);setPreview(false)}
 async function rename(){if(!current)return;const title=window.prompt('新笔记名称',noteTitle(current.content,current.path));if(!title)return;const next=await renameNote(current.path,safeNoteFilename(title,notes.filter(note=>note.path!==current.path).map(note=>note.path)));if(!next)return;setNotes(items=>items.map(note=>note.path===current.path?{...note,path:next}:note));setActive(next)}
 async function remove(){if(!current||!window.confirm(`删除“${noteTitle(current.content,current.path)}”？此操作不可撤销。`))return;await deleteNote(current.path);const next=notes.filter(note=>note.path!==current.path);setNotes(next);setActive(next[0]?.path||'')}
 async function saveSql(){if(!currentSql.trim())return onNotify('当前查询为空');if(!current){const path=safeNoteFilename('当前查询',notes.map(note=>note.path)),content=appendSqlToNote('# 当前查询\n',currentSql);await writeNote(path,content);setNotes(items=>[{path,content,modifiedMs:Date.now()},...items]);setActive(path);onNotify('当前 SQL 已保存到新笔记');return}update(appendSqlToNote(current.content,currentSql));onNotify('当前 SQL 已加入笔记')}
 if(!isTauri())return <section className="notes-workspace notes-empty"><div className="notes-empty-card"><span className="notes-empty-icon">▤</span><h1>个人笔记</h1><p>个人笔记读取本机 Markdown 目录，仅桌面客户端可用。</p></div></section>
 if(!directory)return <section className="notes-workspace notes-empty"><div className="notes-empty-card"><span className="notes-empty-icon">▤</span><h1>建立个人笔记库</h1><p>选择一个本地目录后，即可浏览、编辑和搜索其中的 Markdown 文件。</p><small>目录完全保存在本机，GeminiDB Studio 不会上传笔记内容。</small><button className="primary" onClick={()=>void choose()}>选择 Markdown 目录</button></div></section>
 return <section className="notes-workspace"><aside className="notes-sidebar"><header><div><b>个人笔记</b><small title={directory}>{directory}</small></div><button onClick={()=>void create()} title="新建笔记" aria-label="新建笔记">＋</button></header><div className="notes-search"><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索标题、正文或标签"/><button className="notes-change-directory" onClick={()=>void choose()} title="更换目录" aria-label="更换目录"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6h7l2 2h9v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><path d="M8 14h8M13 11l3 3-3 3"/></svg><span>更换目录</span></button></div><div className="notes-list">{filtered.map(note=><button key={note.path} className={note.path===active?'active':''} onClick={()=>setActive(note.path)}><b>{noteTitle(note.content,note.path)}</b><small>{noteTags(note.content).map(tag=>`#${tag}`).join(' ')||note.path}</small></button>)}{!filtered.length&&<p>没有匹配的笔记</p>}</div></aside><article className="notes-editor">{current?<><header><div><h1>{noteTitle(current.content,current.path)}</h1><small>{status||current.path}</small></div><div><button onClick={()=>void saveSql()}>保存当前 SQL</button><button onClick={()=>setPreview(value=>!value)}>{preview?'编辑':'预览'}</button><button onClick={()=>void rename()}>重命名</button><button className="danger" onClick={()=>void remove()}>删除</button></div></header>{preview?<div className="notes-preview"><div className="notes-preview-content">{parseMarkdown(current.content).map((block,index)=>{if(block.type==='heading')return createElement(`h${block.level}`,{key:index},block.text);if(block.type==='code')return <figure key={index}><figcaption>{block.language||'text'}{['influxql','sql'].includes(block.language)&&<button onClick={()=>onOpenSql(block.text)}>放入新查询</button>}</figcaption><pre><code>{block.text}</code></pre></figure>;if(block.type==='table')return <table key={index}><thead><tr>{block.headers.map((value,i)=><th key={i}>{value}</th>)}</tr></thead><tbody>{block.rows.map((row,i)=><tr key={i}>{row.map((value,j)=><td key={j}>{value}</td>)}</tr>)}</tbody></table>;if(block.type==='list'){const Tag=block.ordered?'ol':'ul';return <Tag key={index}>{block.items.map((item,i)=><li key={i}>{item}</li>)}</Tag>}return <p key={index}>{block.text}</p>})}</div></div>:<textarea aria-label="Markdown 编辑器" value={current.content} onChange={event=>update(event.target.value)} spellCheck={false}/>}</>:<div className="notes-welcome"><div><span className="notes-empty-icon">▤</span><h2>还没有笔记</h2><p>新建一篇 Markdown 笔记开始记录。</p><button className="primary" onClick={()=>void create()}>新建笔记</button></div></div>}</article></section>
}
