import { useState } from 'react'
import type { WorkspaceTab } from './types'
import { resolveWorkspaceTabName } from './workspace-tab-rename'

export default function WorkspaceTabs({tabs,activeTabId,onSelect,onClose,onAddQuery,onRenameQuery}:{tabs:WorkspaceTab[];activeTabId:string;onSelect:(id:string)=>void;onClose:(id:string)=>void;onAddQuery:()=>void;onRenameQuery:(id:string,name:string)=>void}){
  const [editingId,setEditingId]=useState(''),[draft,setDraft]=useState('')
  function beginRename(id:string,name:string){setEditingId(id);setDraft(name)}
  function finishRename(id:string,original:string){const name=resolveWorkspaceTabName(original,draft,'commit');setEditingId('');if(name!==original)onRenameQuery(id,name)}
  return <div className="workspace-tabs" role="tablist">{tabs.map(tab=><div key={tab.id} role="tab" tabIndex={editingId===tab.id?-1:0} aria-selected={tab.id===activeTabId} className={`query-tab ${tab.kind==='measurement-data'?'measurement-data-tab':''} ${tab.id===activeTabId?'active':''}`} onClick={()=>onSelect(tab.id)} onKeyDown={event=>{if(editingId!==tab.id&&(event.key==='Enter'||event.key===' '))onSelect(tab.id)}} onDoubleClick={tab.kind==='query'?event=>{event.stopPropagation();beginRename(tab.id,tab.name)}:undefined} title={tab.kind==='query'?'双击重命名':tab.name}>{editingId===tab.id?<input className="query-tab-name-input" autoFocus value={draft} onFocus={event=>event.currentTarget.select()} onClick={event=>event.stopPropagation()} onDoubleClick={event=>event.stopPropagation()} onChange={event=>setDraft(event.target.value)} onBlur={()=>finishRename(tab.id,tab.name)} onKeyDown={event=>{event.stopPropagation();if(event.key==='Enter'){event.preventDefault();finishRename(tab.id,tab.name)}else if(event.key==='Escape'){event.preventDefault();setEditingId('');setDraft(resolveWorkspaceTabName(tab.name,draft,'cancel'))}}} aria-label={`重命名 ${tab.name}`}/>:<span>{tab.name}</span>}<button className="close-tab" onClick={event=>{event.stopPropagation();onClose(tab.id)}} aria-label={`关闭 ${tab.name}`}>×</button></div>)}<button className="add-query-tab" onClick={onAddQuery} title="新建查询">＋</button></div>
}
